### ISSUE TITLE
Implement License

### ISSUE THREAD

**Issue by robertsg90** [robertsg90/freecodecamp_tributepage#1]

**Comment by sandmanx** [comment]
I guess you want to add a license to your project?

**Comment by bettersandeep** [comment]
I would love to take this issue. Would a MIT license suffice? If so, then I would require your full name. Cheers !

**Comment by rusrushal13** [comment]
I have created a Pull Request regarding the Same.

**Comment by bettersandeep** [comment]
@robertsg90 Solved the issue with reference to PR #3 .You can close the issue now. Thanks! :)
